In [10]:
faqs = """
In the bustling city of Meridian, there was a small café tucked away in a quiet corner. The café, known as The Morning Brew, was a favorite among the locals. Every morning, the aroma of freshly brewed coffee filled the air, drawing in early risers and night owls alike. The walls of the café were adorned with paintings from local artists, giving it a cozy and artistic vibe.

One of the regulars, an old man named Harold, would always sit by the window with a newspaper in hand. He was a retired teacher and loved to watch the world go by as he sipped his coffee. Across the room, a young woman named Clara worked on her laptop, typing furiously as she worked on her novel. She found inspiration in the hum of the café, surrounded by people yet lost in her own world.

One day, a stranger walked into The Morning Brew. He was a tall man with a kind face and an air of mystery. He ordered a black coffee and sat down at the corner table. His presence intrigued both Harold and Clara. Over the next few days, the stranger became a regular fixture at the café, always sitting in the same spot and quietly observing his surroundings.

Harold, curious by nature, decided to strike up a conversation with the stranger. They talked about the weather, the city, and eventually, their lives. The stranger, whose name was Michael, shared that he was a traveler, always moving from one place to another. He had seen many cities and met many people, but he always felt a sense of loneliness.

As days turned into weeks, Harold, Clara, and Michael formed an unlikely friendship. They shared stories, dreams, and fears, finding comfort in each other's company. The café became more than just a place for coffee; it became a sanctuary for them. They found solace in knowing that no matter where life took them, they had a place to return to.

The Morning Brew, with its warm atmosphere and the bonds formed within its walls, became a symbol of connection and belonging. It was a reminder that even in a bustling city, one could find a sense of home in the most unexpected places.
"""

In [12]:
# Import Libraries
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

In [13]:
tokenizer = Tokenizer()

In [14]:
tokenizer.fit_on_texts([faqs])

In [15]:
tokenizer.word_index

{'the': 1,
 'a': 2,
 'and': 3,
 'in': 4,
 'of': 5,
 'was': 6,
 'he': 7,
 'café': 8,
 'with': 9,
 'to': 10,
 'as': 11,
 'morning': 12,
 'coffee': 13,
 'one': 14,
 'harold': 15,
 'always': 16,
 'by': 17,
 'stranger': 18,
 'became': 19,
 'they': 20,
 'city': 21,
 'brew': 22,
 'it': 23,
 'an': 24,
 'his': 25,
 'clara': 26,
 'her': 27,
 'that': 28,
 'place': 29,
 'bustling': 30,
 'corner': 31,
 'air': 32,
 'walls': 33,
 'from': 34,
 'man': 35,
 'named': 36,
 'world': 37,
 'worked': 38,
 'on': 39,
 'she': 40,
 'found': 41,
 'people': 42,
 'into': 43,
 'at': 44,
 'days': 45,
 'michael': 46,
 'shared': 47,
 'had': 48,
 'many': 49,
 'sense': 50,
 'formed': 51,
 'for': 52,
 'them': 53,
 'its': 54,
 'meridian': 55,
 'there': 56,
 'small': 57,
 'tucked': 58,
 'away': 59,
 'quiet': 60,
 'known': 61,
 'favorite': 62,
 'among': 63,
 'locals': 64,
 'every': 65,
 'aroma': 66,
 'freshly': 67,
 'brewed': 68,
 'filled': 69,
 'drawing': 70,
 'early': 71,
 'risers': 72,
 'night': 73,
 'owls': 74,
 'alike': 

In [21]:
input_sequences = []
for sentence in faqs.split('.'):
    #print(sentence)
    #print(tokenizer.texts_to_sequences([sentence])[0])
    tokenized_sentence = tokenizer.texts_to_sequences([sentence])[0]

    for i in range(1, len(tokenized_sentence)):
        n_gram_sequence = tokenized_sentence[:i+1]
        input_sequences.append(n_gram_sequence)
        #print(n_gram_sequence)

In [22]:
input_sequences

[[4, 1],
 [4, 1, 30],
 [4, 1, 30, 21],
 [4, 1, 30, 21, 5],
 [4, 1, 30, 21, 5, 55],
 [4, 1, 30, 21, 5, 55, 56],
 [4, 1, 30, 21, 5, 55, 56, 6],
 [4, 1, 30, 21, 5, 55, 56, 6, 2],
 [4, 1, 30, 21, 5, 55, 56, 6, 2, 57],
 [4, 1, 30, 21, 5, 55, 56, 6, 2, 57, 8],
 [4, 1, 30, 21, 5, 55, 56, 6, 2, 57, 8, 58],
 [4, 1, 30, 21, 5, 55, 56, 6, 2, 57, 8, 58, 59],
 [4, 1, 30, 21, 5, 55, 56, 6, 2, 57, 8, 58, 59, 4],
 [4, 1, 30, 21, 5, 55, 56, 6, 2, 57, 8, 58, 59, 4, 2],
 [4, 1, 30, 21, 5, 55, 56, 6, 2, 57, 8, 58, 59, 4, 2, 60],
 [4, 1, 30, 21, 5, 55, 56, 6, 2, 57, 8, 58, 59, 4, 2, 60, 31],
 [1, 8],
 [1, 8, 61],
 [1, 8, 61, 11],
 [1, 8, 61, 11, 1],
 [1, 8, 61, 11, 1, 12],
 [1, 8, 61, 11, 1, 12, 22],
 [1, 8, 61, 11, 1, 12, 22, 6],
 [1, 8, 61, 11, 1, 12, 22, 6, 2],
 [1, 8, 61, 11, 1, 12, 22, 6, 2, 62],
 [1, 8, 61, 11, 1, 12, 22, 6, 2, 62, 63],
 [1, 8, 61, 11, 1, 12, 22, 6, 2, 62, 63, 1],
 [1, 8, 61, 11, 1, 12, 22, 6, 2, 62, 63, 1, 64],
 [65, 12],
 [65, 12, 1],
 [65, 12, 1, 66],
 [65, 12, 1, 66, 5],
 [65, 12

In [25]:
max_length = max([len(x) for x in input_sequences])

In [36]:
max_length

25

In [26]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
pad_sequences = pad_sequences(input_sequences, maxlen=max_length, padding='pre')
pad_sequences

array([[  0,   0,   0, ...,   0,   4,   1],
       [  0,   0,   0, ...,   4,   1,  30],
       [  0,   0,   0, ...,   1,  30,  21],
       ...,
       [  0,   0,   0, ...,   4,   1, 196],
       [  0,   0,   0, ...,   1, 196, 197],
       [  0,   0,   0, ..., 196, 197, 198]], dtype=int32)

In [29]:
# Features
X = pad_sequences[:, :-1]

In [30]:
# target
y = pad_sequences[:, -1]

In [31]:
X.shape

(351, 24)

In [32]:
y.shape

(351,)

In [33]:
# on hot encoding
from tensorflow.keras.utils import to_categorical
y = to_categorical(y, num_classes=len(tokenizer.word_index)+1)

In [34]:
y

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], dtype=float32)

In [35]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

In [37]:
model = Sequential()
model.add(Embedding(input_dim=len(tokenizer.word_index)+1, output_dim=100, input_length=max_length-1))
model.add(LSTM(150))
model.add(Dense(len(tokenizer.word_index)+1, activation='softmax'))

In [38]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [40]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 24, 100)           19900     
                                                                 
 lstm (LSTM)                 (None, 150)               150600    
                                                                 
 dense (Dense)               (None, 199)               30049     
                                                                 
Total params: 200549 (783.39 KB)
Trainable params: 200549 (783.39 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [41]:
X

array([[  0,   0,   0, ...,   0,   0,   4],
       [  0,   0,   0, ...,   0,   4,   1],
       [  0,   0,   0, ...,   4,   1,  30],
       ...,
       [  0,   0,   0, ..., 195,   4,   1],
       [  0,   0,   0, ...,   4,   1, 196],
       [  0,   0,   0, ...,   1, 196, 197]], dtype=int32)

In [42]:
model.fit(X, y, epochs=100)

Epoch 1/100
11/11 [==============================] - 3s 41ms/step - loss: 5.2847 - accuracy: 0.0541
Epoch 2/100
11/11 [==============================] - 1s 47ms/step - loss: 5.1002 - accuracy: 0.0627
Epoch 3/100
11/11 [==============================] - 0s 40ms/step - loss: 4.9558 - accuracy: 0.0570
Epoch 4/100
11/11 [==============================] - 1s 48ms/step - loss: 4.8921 - accuracy: 0.0855
Epoch 5/100
11/11 [==============================] - 0s 42ms/step - loss: 4.8597 - accuracy: 0.0627
Epoch 6/100
11/11 [==============================] - 0s 46ms/step - loss: 4.8361 - accuracy: 0.0997
Epoch 7/100
11/11 [==============================] - 0s 43ms/step - loss: 4.8182 - accuracy: 0.0940
Epoch 8/100
11/11 [==============================] - 1s 49ms/step - loss: 4.7932 - accuracy: 0.0855
Epoch 9/100
11/11 [==============================] - 0s 41ms/step - loss: 4.7483 - accuracy: 0.0969
Epoch 10/100
11/11 [==============================] - 1s 46ms/step - loss: 4.6896 - accuracy: 0.1083

In [54]:
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
import numpy as np

# define the text and tokenizer
text = "there"

for i in range(5):

  # tokenize
  token_text = tokenizer.texts_to_sequences([text])[0]

  # pad
  pad_text = pad_sequences([token_text], maxlen=max_length-1, padding='pre')

  # prediction = model.predict(pad_text).shape
  # prediction
  pos = np.argmax(model.predict(pad_text))

  for word, index in tokenizer.word_index.items():
      if index == pos:
          text += ' ' + word
          print(text)

1/1 [==============================] - 0s 24ms/step
there was
1/1 [==============================] - 0s 23ms/step
there was a
1/1 [==============================] - 0s 23ms/step
there was a reminder
1/1 [==============================] - 0s 24ms/step
there was a reminder that
1/1 [==============================] - 0s 25ms/step
there was a reminder that even


In [57]:
# define the text and tokenizer
text = "I love"

for i in range(5):

  # tokenize
  token_text = tokenizer.texts_to_sequences([text])[0]

  # pad
  pad_text = pad_sequences([token_text], maxlen=max_length-1, padding='pre')

  # prediction = model.predict(pad_text).shape
  # prediction
  pos = np.argmax(model.predict(pad_text))

  for word, index in tokenizer.word_index.items():
      if index == pos:
          text += ' ' + word
          print(text)

1/1 [==============================] - 0s 25ms/step
I love found
1/1 [==============================] - 0s 23ms/step
I love found inspiration
1/1 [==============================] - 0s 25ms/step
I love found inspiration in
1/1 [==============================] - 0s 26ms/step
I love found inspiration in the
1/1 [==============================] - 0s 26ms/step
I love found inspiration in the hum
